### ISSUE TITLE
Issue on subprocess.Popen

### ISSUE THREAD

**Issue by Thuliumitation** [nandiniproothi/notion-discord-rpc#2]
Traceback (most recent call last):
  File "G:\notion-discord-rpc\script.py", line 5, in <module>
    (var3, tError) = Popen(['osascript', 'Setup.scpt'], stdout=PIPE, universal_newlines=True).communicate()
  File "I:\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "I:\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I can't really find an 'osascript' file in the directory. Any fix?

**Comment by albatrosspreacher** [comment]
Hi @Thuliumitation,
Thanks for reporting this issue. Unfortunately, as mentioned in the README, this script only works on macOS (since it uses AppleScript). I believe you are trying to run it on a Windows system. I don't intend to create a script for Windows any time soon but if you come up with something, do open a PR :D
